[package]
name = "leetcode"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]

[[bin]]
name = "reverse-string"
path = "reverse_string/main.rs"

[[bin]]
name = "valid-palindrome"
path = "valid_palindrome/main.rs"

[[bin]]
name = "merge-sorted-array"
path = "merge_sorted_array/main.rs"
